config/routes.rb
Freefood::Application.routes.draw do
  resources :events

  match '/addevent', :to => 'events#new'
  
  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :host, :location, :description, :when, :host_email, :featured, :going
  
  validates :name, :presence => true,
            :length => { :minimum => 3, :maximum => 30 }
  
  validates :host, :presence => true,
            :length => { :minimum => 3, :maximum => 50 }
  
  validates :location, :presence => true,
            :length => { :minimum => 3, :maximum => 30 }
            
  validates :description, :presence => true,
            :length => { :within => 10..300 }
            
  validates :host_email, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @title = "Events"
    @events = Event.all
  end
  
  def show
    @event = Event.find(params[:id])
    @title = @event.name
  end
  
  def new
    @event = Event.new
    @title = "Add Event"
  end
  
  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to @event
    else
      @title = "Add Event"
      render 'new'
    end
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def events
    @title = "Events"
  end

  def singleEvent
    @title = "Event Description"
  end
  
  def addEvent
    @title = "Add Event"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis
  def title
    base_title = "Starving Student"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/events/add.html.erb
<h1>Events#add</h1>
<p>Find me in app/views/events/add.html.erb</p>

app/views/events/index.html.erb
<div id="indexHeader">Events in the next 24 hours</div>

<ul class="events">
	<% @events.each do |event| %>
		<li>
			<span id="eventTitle"><%= link_to event.name, event %></span> <br />
			<span id="eventHost"><%= event.host %></span> <br />
			<span id="eventLocation"><%= event.location %></span>
		</li>
	<% end %>
</ul>

<div class="staticLinkBox">
	<%= link_to "Add your event and increase visibility", addevent_path, :class => "addEventButton" %>
</div>

<div class="staticLinkBox">
	<%= link_to "About Starving Student", '#', :class => "aboutUsButton" %>
</div>

app/views/events/new.html.erb
<h1>Submit your event</h1>

<%= form_for(@event) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :host_email %><br />
    <%= f.text_field :host_email %>
  </div>
  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="showHeader"> 
	<span id="showHeaderName"><%= @event.name %></span> <br />
	<span id="showHeaderHost"><%= @event.host %></span>
</div>

<div class="showBody">
	<div id="showGoing"> 
		56 people going <div id="showGoingButton">I'm Going</div>
	</div>
	<div id="showDescription">
		<%= @event.description %>
	</div>
	<div id="showLocation">
		happening at <%= @event.location %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
	<p>© Starving Student 2012</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
	<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
	<link rel="apple-touch-icon-precomposed" href="assets/starvingStudentIcon.png">
  <%= stylesheet_link_tag 'main' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<%= image_tag("header.png", :alt => "Starving Student", :class => "header") %>
	</header>
	
	<%= yield %>
	
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/main/addEvent.html.erb
<h1>Main#addEvent</h1>
<p>Find me in app/views/main/addEvent.html.erb</p>

app/views/main/events.html.erb
<h1>Haw haw haw</h1>
<p>we be listen da events mon</p>

app/views/main/singleEvent.html.erb
<h1>Main#singleEvent</h1>
<p>Find me in app/views/main/singleEvent.html.erb</p>